export const CompanyNames = [
  "ECorp",
  "MegaCorp",
  "Bachman & Associates",
  "Blade Industries",
  "NWO",
  "Clarke Incorporated",
  "OmniTek Incorporated",
  "Four Sigma",
  "KuaiGong International",
  "Fulcrum Technologies",
  "Storm Technologies",
  "DefComm",
  "Helios Labs",
  "VitaLife",
  "Icarus Microsystems",
  "Universal Energy",
  "Galactic Cybersystems",
  "AeroCorp",
  "Omnia Cybersystems",
  "Solaris Space Systems",
  "DeltaOne",
  "Global Pharmaceuticals",
  "Nova Medical",
  "Central Intelligence Agency",
  "National Security Agency",
  "Watchdog Security",
  "LexoCorp",
  "Rho Construction",
  "Alpha Enterprises",
  "Aevum Police Headquarters",
  "SysCore Securities",
  "CompuTek",
  "NetLink Technologies",
  "Carmichael Security",
  "FoodNStuff",
  "Joe's Guns",
  "Omega Software",
 "Noodle Bar",
]
